const Settings = () => {
  return (
    <div className="h-full mx-auto w-3/4">
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, excepturi mollitia vero distinctio reprehenderit iste minus sit assumenda cumque sint deleniti earum aut, unde incidunt nihil tempora ex adipisci minima?</p>
    </div>
  );
};

export default Settings;
